# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6c4048a36955cddfca9ebc546c6d57f1"
name = "jeet-dot-dev-banner-app"
application_url = "https://pros-jersey-vancouver-announcement.trycloudflare.com"
embedded = true
handle = "jeet-dot-dev-banner-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://pros-jersey-vancouver-announcement.trycloudflare.com/auth/callback", "https://pros-jersey-vancouver-announcement.trycloudflare.com/auth/shopify/callback", "https://pros-jersey-vancouver-announcement.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
